### ISSUE TITLE
Need to stringify ~body value?

### ISSUE THREAD

**Issue by hanishi** [tsnobip/reason-lambda#1]
When the function is invoked after having 'sls deploy' ed, `body` is returned in a JSON as a property identifying its value as what was passed to the `~body` parameter when `Response.make` is called. I think AWS API gateway is supposed to reformat this and would only return whatever the value the `~body` dereferences as the actual payload of the response. 

When I tried the following, I got the expected response:
```
let body = Json.Encode.(object_([("greetings", string(greetings))]));
    Response.make(~statusCode=200,~body=Json.stringify(body), ())->Js.Promise.resolve;
```

**response**
```
{"greetings":"Hello Anon, you're making this request to reason-sls-example-dev-hello from Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36"}
```

otherwise, API Gateway returns this
```
{"body": {"greetings":"Hello Anon, you're making this request to reason-sls-example-dev-hello from Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36"} }
```

I think `~body` needs to be a string thus `Response.t('a)` should really be `Response.t(string)`?

**Comment by tsnobip** [comment]
Thank you very much for noticing it @hanishi, indeed the bindings were incorrect, you either need to directly return the body of your response or you have to stringify it if you return it as a `body` field of the response object.

V0.2.0 fixes this issue.

Don't hesitate to tell me if you're not happy with the new bindings or if you find anything wrong.

**Comment by hanishi** [comment]
I think I figured out what was not working. I forked your repo(for experimental purpose) and made my own changes to your latest commit. Your initial version was actually close.  Applying `Js.Json.stringifyAny` to whatever goes to the `body` apparently fixed the issue. (I am new to ReasonML so my fix may not be as good as yours though)

https://github.com/hanishi/reason-lambda/blob/master/src/V2.re#L6-L54

**Comment by tsnobip** [comment]
the benefit of the payload v2 is not having to stringify the body, that's why I wanted to avoid that and instead wrote 2 bindings, one (`fromBody`) that allows to construct a response without stringifying the body and another one (`make`) that allows to customize the response but that requires a stringified body (AWS docs are not that clear but I tested it and it is indeed required).

Now that I'm thinking about it, these bindings could be simplified down to:
```reasonml
type handler('a) = (Event.t, Context.t) => Js.Promise.t('a);
```
where `'a` could be a `Response.t` when you need to customize the response, what do you think of that?

**Comment by tsnobip** [comment]
hmm, well actually no, it's better the way it is today, with this simplification, you couldn't write a function that would dynamically return a body or a custom response. My bad!

Is there something that doesn't work for you with the current implementation?

**Comment by hanishi** [comment]
It was kind of hard to figure out what was going on with [@unboxed] as I am relatively new to this language, although I did learn a lot from your source code though.

I studied these [GADTs: A primer](https://sketch.sh/s/yH0MJiujNSiofDWOU85loX/) and [Union types in BuckleScript](https://bucklescript.github.io/blog/2020/02/07/union-types-in-bucklescript) 
It was kind of hard to grasp, as I am new to ReasonML/OCaml, what these concepts bring to your last update.

>you couldn't write a function that would dynamically return a body or a custom response

My proficiency in the language is not adequate to understand this yet. :)

So with the current implementation, 
1) I have to stringify what goes to `~body` explicitly when using `make`
2) I don't need to stringify when `fromBody` is used?

**Comment by tsnobip** [comment]
> It was kind of hard to figure out what was going on with [@unboxed] as I am relatively new to this language, although I did learn a lot from your source code though.
> 
> I studied these [GADTs: A primer](https://sketch.sh/s/yH0MJiujNSiofDWOU85loX/) and [Union types in BuckleScript](https://bucklescript.github.io/blog/2020/02/07/union-types-in-bucklescript)
> It was kind of hard to grasp, as I am new to ReasonML/OCaml, what these concepts bring to your last update.

I could have used [`%identity`](https://bucklescript.github.io/docs/en/intro-to-external#special-identity-external) external instead of `unboxed`, but basically, what `unboxed` allows for bindings is the ability to construct an "opaque" type from different input types. That's what is explained the union type blog post. GADT is a pretty advanced concept but I'm barely scratching the surface of it here ^^

> > you couldn't write a function that would dynamically return a body or a custom response
> 
> My proficiency in the language is not adequate to understand this yet. :)

Well imagine a pretty simple example where your lambda function defines an upsert of an `Item.t` that returns the inserted/updated `Item.t`, you'd likely respond with the item and a `200` (`OK`) status code when updated (so by directly returning an `Item.t` in the bindings I was thinking of) and with the item and a `201` (`CREATED`) status code when inserted (this by using the `Response.make` function) so the two branches of the function would have different types (`Item.t` != `Response.t`) which is not possible in OCaml. You'd have the same problem if you want to possibly return an error response for example. Do you follow me?

> So with the current implementation,
> 
>     1. I have to stringify what goes to `~body` explicitly when using `make`
> 
>     2. I don't need to stringify when `fromBody` is used?

Yes exactly 😃

**Comment by hanishi** [comment]
Sorry for this late response. I am based in Tokyo, so it was kind of late when I posted my last comment. I just woke up. 
Thank you for taking the time to explain everything above! I am still a novice in a strongly typed language world, so it would probably take some time to fully understand what you kindly explained to me (and no offense, I am learning, and I find it very interesting!) 😊  It sounded like [Phantom Types](https://medium.com/reasontraining/phantom-types-in-reasonml-1a4cfc18d999), but probably not. Anyway thank you for doing this, I appreciate your work and kindness.
